# Generated by Django 4.2.1 on 2023-05-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
