# Generated by Django 4.2.1 on 2023-05-13 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="listing",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="listings",
            field=models.ManyToManyField(blank=True, to="auctions.listing"),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
