# Generated by Django 4.2.1 on 2023-05-14 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_watchlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="listings",
            field=models.ManyToManyField(
                blank=True, related_name="watchlists", to="auctions.listing"
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
