# Generated by Django 4.2.1 on 2023-05-25 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_posts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Posts",
            new_name="Post",
        ),
    ]
