# Generated by Django 4.2.1 on 2023-05-23 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_user_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                default=0,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
